sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 5.4
      dist: precise
    - php: 5.6
    - php: 7.2
    - php: 7.3
branches:
  except:
    - /^dist/
    - /^release/
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh